pipeline {

    agent any

    environment {
        IMAGE_NAME = "muthupandimathi/multitenantapi"
        IMAGE_TAG = "${BUILD_NUMBER}"
        KUBECONFIG = "C:\\Users\\HP ZBOOK FURY\\.kube\\config"
    }

    stages {

        stage('Restore & Publish') {
            steps {
                dir('MultiTenantAPI') {
                    bat 'dotnet restore'
                    bat 'dotnet publish -c Release -o publish'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('MultiTenantAPI') {
                    bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-login',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat 'echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin'
                }
            }
        }

        stage('Docker Push') {
            steps {
                bat 'docker push %IMAGE_NAME%:%IMAGE_TAG%'
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                dir('MultiTenantAPI') {

                    bat 'kubectl apply -f kubernetes\\deployment.yaml'

                    bat 'kubectl set image deployment/multitenantapi multitenantapi=%IMAGE_NAME%:%IMAGE_TAG%'

                    bat 'kubectl rollout status deployment/multitenantapi'
                }
            }
        }

    }

    post {

        success {
            echo "Build Successful"
        }

        failure {
            echo "Build Failed"
        }

        always {
            bat 'docker image prune -f'
        }
    }
}