pipeline {

    agent any

    environment {
        IMAGE_NAME = "muthupandimathi/multitenantapi"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Build .NET') {
            steps {
                dir('MultiTenantAPI') {
                    bat 'dotnet restore'
                    bat 'dotnet publish -c Release -o publish'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('MultiTenantAPI') {
                    bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-login',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                }
            }
        }

        stage('Docker Push') {
            steps {
                bat 'docker push %IMAGE_NAME%:%IMAGE_TAG%'
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                dir('MultiTenantAPI') {
                    bat 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}